In [1]:
import os
import math
import numpy as np
import random

data_dir = os.path.join('..','data')

def standardize(X, min_vector, max_vector):
    print type(X)
    min_vector=np.amin(X, axis=0)
    max_vector=np.amax(X, axis=0)
    X=(X-min_vector)/(max_vector-min_vector)
    return X

def LinReg_ReadInputs(data_dir):
    
    #function that reads all four of the Linear Regression csv files and outputs
    #them as such

    #Input
    #filepath : The path where all the four csv files are stored.

    #output 
    #XTrain : NxK+1 numpy matrix containing N number of K+1 dimensional training features
    XTrain = np.genfromtxt(os.path.join(data_dir, 'LinReg_XTrain.csv'), delimiter=',')
    #yTrain : Nx1 numpy vector containing the actual output for the training features
    yTrain = np.genfromtxt(os.path.join(data_dir, 'LinReg_yTrain.csv'), delimiter=',')
    #XTest  : nxK+1 numpy matrix containing n number of K+1 dimensional testing features
    XTest = np.genfromtxt(os.path.join(data_dir, 'LinReg_XTest.csv'), delimiter=',')
    #yTest  : nx1 numpy vector containing the actual output for the testing features
    yTest = np.genfromtxt(os.path.join(data_dir,'LinReg_yTest.csv'), delimiter=',')
    #print XTrain
    #standardizing
    XTrain_max=np.amax(XTrain, axis=0)
    XTrain_min=np.amin(XTrain, axis=0)
    XTrain_st=standardize(XTrain, XTrain_min, XTrain_max)
    XTest_st=standardize(XTest, XTrain_min, XTrain_max)
    #adding column of 1s
    XTrain_st_ones = np.insert(XTrain_st, 0, 1, axis=1)
    XTest_st_ones = np.insert(XTest_st, 0, 1, axis=1)
    return (XTrain_st_ones, yTrain, XTest_st_ones, yTest)
    
def LinReg_CalcObj(X, y, w):
    
    #function that outputs the value of the loss function L(w) we want to minimize.

    #Input
    #w      : numpy weight vector of appropriate dimensions
    #AND EITHER
    #XTrain : Nx(K+1) numpy matrix containing N number of K+1 dimensional training features
    #yTrain : Nx1 numpy vector containing the actual output for the training features
    #OR
    #XTest  : nx(K+1) numpy matrix containing n number of K+1 dimensional testing features
    #yTest  : nx1 numpy vector containing the actual output for the testing features
      
    #Output
    #loss   : The value of the loss function we want to minimize
    print X.shape
    print y.shape
    print w
    X_w = np.dot(X, w)
    print X_w.shape
    A = np.subtract(y, X_w)
    lossVal = -(np.multiply(A.transpose(),A))/float(len(A)) 
    #print "loss values", lossVal
    #print lossVal.shape
    return lossVal

def LinReg_CalcSG(x_i, y_i, w):
    
    #Function that calculates and returns the stochastic gradient value using a
    #particular data point (x, y).
    #Input
    #x : 1x(K+1) dimensional feature point
    #y : Actual output for the input x
    #w : (K+1)x1 dimensional weight vector 
    #Output
    #sg : gradient of the weight vector
    
    wt_xi=np.dot(w.transpose(),x_i)
    first_term=np.negative(np.subtract(y_i, wt_xi))
    result=np.multiply(first_term, x_i)
    return result

def LinReg_UpdateParams(w, sg, eta):
    
    #Function which takes in your weight vector w, the stochastic gradient
    #value sg and a learning constant eta and returns an updated weight vector w.
    #Input
    #w  : (K+1)x1 dimensional weight vector before update 
    #sg : gradient of the calculated weight vector using stochastic gradient descent
    #eta: Learning rate
    #Output
    #w  : Updated weight vector
    w_new=np.subtract(w,np.dot(eta,sg))
    return w_new
    
def LinReg_SGD(XTrain, yTrain, XTest, yTest):
    
    #Stochastic Gradient Descent Algorithm function

    #Input
    #XTrain : Nx(K+1) numpy matrix containing N number of K+1 dimensional training features
    #yTrain : Nx1 numpy vector containing the actual output for the training features
    #XTest  : nx(K+1) numpy matrix containing n number of K+1 dimensional test features
    #yTest  : nx1 numpy vector containing the actual output for the test features
    
    #Output
    #w    : Updated Weight vector after completing the stochastic gradient descent
    #trainLoss : vector of training loss values at each epoch
    #testLoss : vector of test loss values at each epoch
    w=np.array([0.5]*len(XTrain[0]))
    iterations = 0
    datapoints=[]
    trainLoss = []
    testLoss = []
    epochs = 0
    print XTrain.shape
    print XTest.shape
    print yTrain.shape
    print yTest.shape
    while (epochs <= 100):
        iterations += 1
        i=random.randint(0,len(yTrain)-1)
        if i not in datapoints: datapoints.append(i)
        eta=0.5/math.sqrt(iterations)
        grad_i=LinReg_CalcSG(XTrain[i], yTrain[i], w)
        w = np.subtract(w, np.dot(eta, grad_i))
        if (len(datapoints)==len(XTrain)-1): 
            Tloss=LinReg_CalcObj(XTrain, yTrain, w)
            trainLoss.append(loss)
            tloss=LinReg_CalcObj(XTest, yTest, w)
            trainLoss.append(loss)
            epochs+=1
    return (w, trainLoss, testLoss)
    
def plot():     # This function's results should be returned via gradescope and will not be evaluated in autolab.
    
    return None

XTrain, yTrain, XTest, yTest = LinReg_ReadInputs(data_dir)

IOError: [Errno 2] No such file or directory: '..\\data\\LinReg_XTrain.csv'

In [44]:
LinReg_ReadInputs(data_dir)

(array([[  1.00000000e+00,   1.38483218e-03,   5.12426339e-02, ...,
           3.33077120e-02,   1.00000000e+00,   8.09633615e-03],
        [  1.00000000e+00,   5.55097598e-03,   0.00000000e+00, ...,
           3.03303303e-02,   4.74519520e-01,   2.10210210e-02],
        [  1.00000000e+00,   1.56568214e-04,   0.00000000e+00, ...,
           2.82700422e-02,   5.58227848e-01,   1.87763713e-02],
        ..., 
        [  1.00000000e+00,   0.00000000e+00,   5.06419542e-02, ...,
           4.70572487e-02,   1.00000000e+00,   1.62799913e-02],
        [  1.00000000e+00,   6.39624641e-04,   0.00000000e+00, ...,
           4.64154180e-02,   1.00000000e+00,   2.90096362e-02],
        [  1.00000000e+00,   4.54163140e-04,   6.61235717e-02, ...,
           5.21053745e-02,   1.00000000e+00,   3.81929750e-02]]),
 array([ 43.5,  21.9,  20.1,  38.7,  24.5,  25. ,  19.3,  50. ,  31.1,
         17.8,  23.2,  33. ,  23.2,  23.9,  25. ,  13.6,  27.5,  14.9,
         34.9,  17.4,  31.2,  19.9,  18.2,  19.6, 

In [2]:
X,y=LinReg_ReadInputs(data_dir)[0],LinReg_ReadInputs(data_dir)[1]
features=len(X[0])
w=[0.5]*features
w=np.array(w)
LinReg_CalcObj(X, y, w)

IOError: [Errno 2] No such file or directory: '..\\data\\LinReg_XTrain.csv'

In [79]:
x=[2,3,7]
y=4
w=np.array([0.5, 0.5, 0.5])
LinReg_CalcSG(x, y, w)

array([  4.,   6.,  14.])

In [52]:
XTrain_toy=np.array[[1.,1.],[1.,2.],[1.,3.],[1.,4.],[1.,5.]]
yTrain_toy=np.array[0.9,1.6,1.9,2.6,3.0]


TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'

In [95]:
XTrain, XTest, yTrain, yTest = LinReg_ReadInputs(data_dir)
LinReg_SGD(XTrain, yTrain, XTest, yTest)

(365L, 14L)
(365L,)
(41L, 14L)
(41L,)


KeyboardInterrupt: 

In [97]:
X,y=LinReg_ReadInputs(data_dir)[0],LinReg_ReadInputs(data_dir)[1]
features=len(X[0])
w=[0.5]*features
LinReg_CalcObj(X, y, w)

NameError: global name 'asint' is not defined

In [100]:
XTrain_toy=[[1.0,1.0],[1.0,2.0],[1.0,3.0],[1.0,4.0],[1.0,5.0]]
XTrain=np.array(XTrain_toy)
yTrain_toy=[0.9,1.6,1.9,2.6,3.0]
yTrain=np.array(yTrain_toy)
features=len(XTrain[0])
w=[0.5]*features
w=np.array(w)
w=w.transpose()
LinReg_CalcObj(XTrain, yTrain, w)

(5L, 2L)
(5L,)
[ 0.5  0.5]
(5L,)


array([-0.002, -0.002, -0.002, -0.002, -0.   ])